<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\VarDumper\\' => array($vendorDir . '/symfony/var-dumper'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Pelago\\' => array($vendorDir . '/pelago/emogrifier/Classes'),
    'DebugBar\\' => array($vendorDir . '/maximebf/debugbar/src/DebugBar'),
);
